- name: tast level variables
  hosts: local
  connection: local
  vars:
    names: ashok
    cource: devscepos
  tasks:
  - name: printing the variables
    vars:
      cource: salesforce
    ansible.builtin.debug:
      msg: "i am {{ name }}, i am learining {{cource}}"