- name: advacnce loops
  hosts: local
  connection: local

  tasks:
  - name: advacnce loo[s in ansible]
    ansible.builtin.debug:
      names: {{ item.names }}
      addresss: {{item.addresss}}
    loop:
    - {names: "ashok", addresss: "jeevakona"}
    - {names: "murali", addresss: "nagar"}