- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    number: 11
  tasks:
  - name: checking the num range
    ansible.builtin.debug:
      msg: yes the num is greter then {{ number }}
    when: number > 10
